services:
  - type: web
    name: crud-app-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: PORT
        value: 3001
      - key: MONGODB_URI
        fromDatabase:
          name: mongodb
          property: connectionString 